export enum GameState {
    WAITING_FOR_PLAYERS = "WAITING_FOR_PLAYERS",
    SUBMIT_TEXT = "SUBMIT_TEXT",
    SUBMIT_IMAGE = "SUBMIT_IMAGE",
    SUBMIT_VOTE = "SUBMIT_VOTE",
    CURRENT_RESULT = "CURRENT_RESULT",
    GAME_OVER = "GAME_OVER"
}